version: "3.8"

services:
  db:
    image: mysql:latest
    container_name: rise-of-self-db
    environment:
      MYSQL_ROOT_PASSWORD: mi_contrasena_super_secreta
      MYSQL_DATABASE: rise_of_self_db
      MYSQL_USER: santi_hero
      MYSQL_PASSWORD: mi_pass_123
    ports:
      - "3306:3306"

    volumes:
      - ./db_scripts:/docker-entrypoint-initdb.d

  backend:
    build: ./rise-of-self-backend
    container_name: rise-of-self-backend
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./rise-of-self-web
    container_name: rise-of-self-frontend
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true
    depends_on:
      - backend
